export const MAIN_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const ALBUM_ROUTE = '/album'
export const REGISTRATION_ROUTE = '/registration'
export const REACT_APP_API_URL = 'http://skubavit.fun/'
export const SECRET = 'secret555777'